#!/usr/bin/env bash
#Script that displays echoes different sentences depending on signals

file=/var/run/myscript.pid

trap 'echo "I hate the kill command"; rm $file; exit' SIGTERM
trap 'rm $file; exit' SIGQUIT
trap 'echo "Y U no love me?!"' SIGINT

echo $$ > $file

until false
do
	echo "To infinity and beyond"
	sleep 2
done
