#!/usr/bin/env bash
#Script that displays "To infinity and beyond" and "I am invincible!!" when receiving SIGTERM

trap 'echo "I am invincible!!!"' SIGTERM

until false
do
        echo "To infinity and beyond"
        sleep 2
done
