#!/usr/bin/env bash
#Script that displays the content of the file /etc/passwd (only username, id, and home directory)

file="/etc/passwd"

while IFS=: read -r username _ userid _ _ _ homedir _
do
	echo "$username:$userid:$homedir"
done < "$file"
