#!/usr/bin/env bash
#Script that prints "Best School" 10 times, but prints "Hi" after 9th iteration

i=1
while [ $i -le 10 ]
do
	echo "Best School"
	if ((i == 9)); then
		echo "Hi"
	fi
	((i++))
done

